### ISSUE TITLE
tsc compile step fails

### ISSUE THREAD

**Issue by TheKrafter** [keyboardcat1/MineRTC#1]
When building, this error occurs during the build step:
```
Starting process 'command 'tsc''. Working directory: /home/krafter/Documents/GitHub/MineRTC/src/main/typescript Command: tsc --build
Successfully started process 'command 'tsc''
src/rtc.ts(98,74): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type 'SignallingRTCPeerConnection'.
  No index signature with a parameter of type 'string' was found on type 'SignallingRTCPeerConnection'.
```

**Comment by TheKrafter** [comment]
This may not be the correct way to do it, but I've at least got the tsc step working with this edit in `src/main/typescript/src/rtc.ts:98`:
```diff
-            if (connection.iceConnectionState === "disconnected") delete connection[connection.to];
+            if (connection.iceConnectionState === "disconnected") delete (connection as any)[connection.to];
```
(From [StackOverflow](https://stackoverflow.com/a/57192972/16263200), im not a TS dev unfortunately)

**Comment by keyboardcat1** [comment]
Hello, thank you for reporting this issue
I just updated EzRTC and typescript to their latest versions and refactored the client script, and it compiles on my machine. Could you check if the issue persists on yours?

**Comment by TheKrafter** [comment]
You changes did solve this issue, but i would reccommend also using npx for browserify:
https://github.com/keyboardcat1/MineRTC/blob/478e9c0b4da859470363d5daf9b7550c9c40799c/build.gradle.kts#L42

Previously adding `$PWD/node_modules/.bin` to PATH was a workaround, but this time I had to use npx instead, which i think is a better solution:
`build.gradle.kts:42`
```
            commandLine("npx", "browserify","build/main.js" , "-o", "../resources/web/static/bundle.js")
```

**Comment by keyboardcat1** [comment]
Thanks, added it.
