### ISSUE TITLE
Configurable Port/Protocol/Domain

### ISSUE THREAD

**Issue by TheKrafter** [keyboardcat1/MineRTC#2]
https://github.com/keyboardcat1/MineRTC/blob/d288b7303db89cb0a17f633ebac6bec14355aad3/src/main/java/io/github/keyboardcat1/minertc/MineRTC.java#L24-L26

It would be nice if the above values could be loaded from a configuration file on the server, and default to something that's not a reserved port, like port `8809`, ip `127.0.0.1`, and protocol `http` (with instructions in the README to change these values in the config).

**Comment by keyboardcat1** [comment]
Fixed with latest PR
